version: "3.9"
services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./firebase:/app
    ports:
      - 4000:4000
      - 9099:9099
      - 8080:8080
      - 8085:8085
      - 9199:9199
    restart: always
